mykey = "petclinic-rancher"
ami = "ami-0cff7528ff583bf9a"
region = "us-east-1"
instance_type = "t3a.medium"
nexus_server_secgr = "petclinic-nexus-server-secgrp"
nexus-server-tag = "Nexus Server of Petclinic"